# Generated by Django 4.2 on 2025-02-21 20:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('verification_status', models.CharField(choices=[('verified', 'Verified'), ('rejected', 'Rejected'), ('pending', 'Pending')], default='pending', max_length=16)),
                ('category', models.IntegerField(choices=[(1, 'Games'), (2, 'Productivity'), (3, 'Social'), (4, 'Education'), (5, 'Health'), (6, 'Other')], default=6)),
                ('version', models.CharField(default='1.0.0', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apps', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='app',
            index=models.Index(fields=['user'], name='appstore_ap_user_id_8e02e0_idx'),
        ),
        migrations.AddIndex(
            model_name='app',
            index=models.Index(fields=['verification_status'], name='appstore_ap_verific_561bc3_idx'),
        ),
        migrations.AddIndex(
            model_name='app',
            index=models.Index(fields=['category'], name='appstore_ap_categor_276f6c_idx'),
        ),
        migrations.AddIndex(
            model_name='app',
            index=models.Index(fields=['verification_status', 'user'], name='appstore_ap_verific_394bb9_idx'),
        ),
        migrations.AddIndex(
            model_name='app',
            index=models.Index(fields=['created_at'], name='appstore_ap_created_9e127f_idx'),
        ),
    ]
