# Generated by Django 4.2 on 2025-02-21 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appstore', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='In US dollars', max_digits=10),
        ),
        migrations.AlterField(
            model_name='app',
            name='verification_status',
            field=models.IntegerField(choices=[(1, 'Verified'), (2, 'Rejected'), (3, 'Pending')], default=3),
        ),
    ]
